### ISSUE TITLE
CRLF line endings cause issues with code blocks

### ISSUE THREAD

**Issue by CptPotato** [EdJoPaTo/markdown-to-standalone-html#59]
I noticed that code blocks sometimes end unexpectedly.

This seems to be an issue with `CRLF` line endings. If the markdown file uses `CRLF` the code block ends after the first line:

~~~
# Hello

```
foo
bar
```
~~~

Renders as:

![image](https://user-images.githubusercontent.com/3957610/197201967-0dd53022-f298-47b9-be37-670aaaa30c78.png)

I worked around this locally by replacing `\r\n` with `\n` in `read_markdown`:

```rust
fn read_markdown(input_path: &Path) -> String {
    if input_path.to_str() == Some("-") {
        let mut input = String::new();
        std::io::stdin()
            .lock()
            .read_to_string(&mut input)
            .expect("failed to read from stdin");
        input
    } else {
        fs::read_to_string(input_path).expect("failed to read markdown file")
    }
    .replace("\r\n", "\n")
}
```

(Also, thanks for making this neat tool 👍)

**Comment by EdJoPaTo** [comment]
Thanks for reporting this! And thanks for the kind words!

I think this should be fixed in the underlying library which handles the markdown parsing but I havnt found a related issue for this there: https://github.com/raphlinus/pulldown-cmark/issues

As you already worked with the code, can you verify that a `cargo update` does not fix this (= the latest dependency versions do not already include a bugfix for this)

If the bug is still there, do you want to report the bug for the pulldown-cmark repo? Otherwise I can do that when I find the time.

**Comment by CptPotato** [comment]
I can still reproduce with `pulldown-cmark = "0.9.2"` as well as the current master branch.

I managed to find an upstream issue, the problem appears to be this: https://github.com/raphlinus/pulldown-cmark/issues/507. I'm not very familiar with markdown parsing, but the issue mentions multiple text events being emitted in the presence of `\r`.

I got it to work roughly following [this related fix](https://github.com/getzola/zola/pull/1911/files):

```diff
diff --git a/src/md2html.rs b/src/md2html.rs
index b569904..9a8e5fe 100644
--- a/src/md2html.rs
+++ b/src/md2html.rs
@@ -13,6 +13,7 @@ pub fn parse(markdown: &str) -> (String, Vec<Heading>) {
     let code_highlighter = Highlighter::new();
     let mut code_language = None;
 
+    let mut accumulated_block = String::new();
     let parser = parser.filter_map(|event| match event {
         Event::Start(Tag::CodeBlock(CodeBlockKind::Fenced(lang))) => {
             code_language = Some(lang.to_string());
@@ -44,14 +45,23 @@ pub fn parse(markdown: &str) -> (String, Vec<Heading>) {
             None
         }
         Event::Text(text) if code_language.is_some() => {
+            accumulated_block += &text;
+            None
+        }
+        Event::End(Tag::CodeBlock(CodeBlockKind::Fenced(_))) if code_language.is_some() => {
             let language = code_language.as_ref().unwrap();
-            let event = match code_highlighter.highlight(language, &text) {
-                Ok(html) => Event::Html(CowStr::from(html)),
-                Err(err) => {
-                    eprintln!("Warning: Failed creating source code formatting: {}", err);
-                    Event::Text(text)
-                }
-            };
+
+            let event = Event::Html(
+                match code_highlighter.highlight(language, &accumulated_block) {
+                    Ok(html) => format!("{html}</code></pre>\n").into(),
+                    Err(err) => {
+                        eprintln!("Warning: Failed creating source code formatting: {}", err);
+                        format!("{accumulated_block}</code></pre>\n").into()
+                    }
+                },
+            );
+
+            accumulated_block.clear();
             code_language = None;
             Some(event)
         }
```

**Comment by EdJoPaTo** [comment]
I guess its a better to discuss the internals of pulldown-cmark in that repo. Given that there isn't much going on it might be a good solution to create the issue and the `.replace("\r\n", "\n")` workaround (with a comment) in this repo.
